# Generated by Django 5.0.2 on 2024-03-03 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_user_confirm_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='confirm_password',
            new_name='confirmPassword',
        ),
    ]
