# Generated by Django 5.0.2 on 2024-03-03 23:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_user_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=13, validators=[django.core.validators.RegexValidator(code='invalid_phone', message='Invalid phone number', regex='^\\+201\\d{9}$')]),
        ),
    ]
